"""ReportLab styles and templates for HeartGuard PDF reports (Phase 10).

Provides a structured, clean, academic/research-style layout with
page numbering, consistent typography, color palettes, and standard disclaimers.
"""

from __future__ import annotations

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

# Theme Colors
PRIMARY_COLOR = colors.HexColor("#1e3a8a")     # Deep clinical blue
SECONDARY_COLOR = colors.HexColor("#0284c7")   # Medium blue
CRITICAL_COLOR = colors.HexColor("#dc2626")    # Alert red
APPOINT_COLOR = colors.HexColor("#d97706")     # Amber warning
MONITOR_COLOR = colors.HexColor("#16a34a")     # Stable green
BG_LIGHT = colors.HexColor("#f8fafc")          # Off-white / light slate
TEXT_DARK = colors.HexColor("#1e293b")         # Slate 800
TEXT_MUTED = colors.HexColor("#64748b")        # Slate 500
BORDER_COLOR = colors.HexColor("#cbd5e1")      # Slate 300

# Standard Disclaimers
STANDARD_DISCLAIMER = (
    "HeartGuard is an academic/research prototype for AI-based heart disease risk assessment. "
    "It is not a medical diagnostic system and does not replace evaluation by a qualified "
    "healthcare professional. Model predictions are experimental computational estimates."
)

CRITICAL_WARNING = (
    "Immediate professional medical evaluation is recommended. "
    "In a real medical emergency, contact local emergency medical services immediately."
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and display total page count."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, total_pages: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_MUTED)

        # Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(54, 750, "HeartGuard AI Risk Assessment Report · Academic/Research Prototype")
            self.setStrokeColor(BORDER_COLOR)
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer (all pages)
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        footer_text = f"Page {self._pageNumber} of {total_pages} · Generated by HeartGuard · Not a medical diagnosis"
        self.drawRightString(558, 32, footer_text)
        self.restoreState()


def get_report_styles() -> dict[str, ParagraphStyle]:
    """Return custom ParagraphStyle dictionary for report generation."""
    base_styles = getSampleStyleSheet()

    styles = {
        "Title": ParagraphStyle(
            "ReportTitle",
            parent=base_styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=PRIMARY_COLOR,
            alignment=0,
            spaceAfter=4,
        ),
        "Subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=SECONDARY_COLOR,
            spaceAfter=15,
        ),
        "Heading1": ParagraphStyle(
            "ReportH1",
            parent=base_styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=PRIMARY_COLOR,
            spaceBefore=12,
            spaceAfter=6,
        ),
        "Heading2": ParagraphStyle(
            "ReportH2",
            parent=base_styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=TEXT_DARK,
            spaceBefore=8,
            spaceAfter=4,
        ),
        "Body": ParagraphStyle(
            "ReportBody",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=TEXT_DARK,
            spaceAfter=6,
        ),
        "BodyBold": ParagraphStyle(
            "ReportBodyBold",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=13.5,
            textColor=TEXT_DARK,
        ),
        "MetaLabel": ParagraphStyle(
            "ReportMetaLabel",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=TEXT_MUTED,
        ),
        "MetaValue": ParagraphStyle(
            "ReportMetaValue",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=TEXT_DARK,
        ),
        "Disclaimer": ParagraphStyle(
            "ReportDisclaimer",
            parent=base_styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=11,
            textColor=TEXT_MUTED,
            spaceAfter=4,
        ),
        "CriticalAlert": ParagraphStyle(
            "ReportCriticalAlert",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=CRITICAL_COLOR,
            spaceAfter=6,
        ),
    }

    return styles
